apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: mysql-init
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "
          CREATE DATABASE IF NOT EXISTS mydb;
          USE mydb;
          CREATE TABLE IF NOT EXISTS messages (
          id INT AUTO_INCREMENT PRIMARY KEY,
          message TEXT
          );
          GRANT ALL PRIVILEGES ON mydb.* TO 'dbadmin'@'%';
          FLUSH PRIVILEGES;"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: MYSQL_ROOT_PASSWORD
      restartPolicy: Never
