apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  # Values are base64 encoded
  MYSQL_ROOT_PASSWORD: YWRtaW4=  # "admin" encoded
  MYSQL_PASSWORD: YWRtaW4=       # "admin" encoded

