name: CI/CD Pipeline for Two-Tier App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./  # Adjust this if your Dockerfile is not in the root directory
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flaskapp:final
        
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        chmod 600 kubeconfig.yaml
        
    - name: Update deployment with new image
      run: |
        export KUBECONFIG=kubeconfig.yaml
        # Update only the image in the deployment
        kubectl set image deployment/two-tier-app two-tier-app=${{ secrets.DOCKER_HUB_USERNAME }}/flaskapp:final
        # Wait for the rollout to complete
        kubectl rollout status deployment/two-tier-app
